// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN7_H
#define UI_SCREEN7_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen7
extern void ui_Screen7_screen_init(void);
extern void ui_Screen7_screen_destroy(void);
extern void ui_event_Screen7(lv_event_t * e);
extern lv_obj_t * ui_Screen7;
extern void ui_event_Container20(lv_event_t * e);
extern lv_obj_t * ui_Container20;
extern lv_obj_t * ui_Container21;
extern void ui_event_Image2(lv_event_t * e);
extern lv_obj_t * ui_Image2;
extern void ui_event_About2(lv_event_t * e);
extern lv_obj_t * ui_About2;
extern lv_obj_t * ui_Label13;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

