// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Image1;
extern void ui_event_Image24(lv_event_t * e);
extern lv_obj_t * ui_Image24;
extern void ui_event_Image3(lv_event_t * e);
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label8;
extern void ui_event_Arc1(lv_event_t * e);
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Container8;
extern void ui_event_Wifi1(lv_event_t * e);
extern lv_obj_t * ui_Wifi1;
extern void ui_event_Setting1(lv_event_t * e);
extern lv_obj_t * ui_Setting1;
extern void ui_event_Image5(lv_event_t * e);
extern lv_obj_t * ui_Image5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

