// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern void ui_event_Container6(lv_event_t * e);
extern lv_obj_t * ui_Container6;
extern void ui_event_Roller1(lv_event_t * e);
extern lv_obj_t * ui_Roller1;
extern lv_obj_t * ui_Container18;
extern void ui_event_settings1(lv_event_t * e);
extern lv_obj_t * ui_settings1;
extern lv_obj_t * ui_alarm;
extern lv_obj_t * ui_timer;
extern lv_obj_t * ui_menu6;
extern void ui_event_wifi5(lv_event_t * e);
extern lv_obj_t * ui_wifi5;
extern void ui_event_home(lv_event_t * e);
extern lv_obj_t * ui_home;
extern lv_obj_t * ui_menu2;
extern void ui_event_menu3(lv_event_t * e);
extern lv_obj_t * ui_menu3;
extern lv_obj_t * ui_bluetooth;
extern void ui_event_games(lv_event_t * e);
extern lv_obj_t * ui_games;
extern lv_obj_t * ui_menu4;
extern lv_obj_t * ui_menu5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

