// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern void ui_event_Screen4(lv_event_t * e);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Container10;
extern void ui_event_Image17(lv_event_t * e);
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Container14;
extern void ui_event_Setting(lv_event_t * e);
extern lv_obj_t * ui_Setting;
extern lv_obj_t * ui_Home1;
extern void ui_event_menu1(lv_event_t * e);
extern lv_obj_t * ui_menu1;
extern lv_obj_t * ui_Image22;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

