// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern void ui_event_Container6(lv_event_t * e);
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Image12;
extern void ui_event_Roller1(lv_event_t * e);
extern lv_obj_t * ui_Roller1;
extern lv_obj_t * ui_Container18;
extern void ui_event_wifi1(lv_event_t * e);
extern lv_obj_t * ui_wifi1;
extern void ui_event_wifi3(lv_event_t * e);
extern lv_obj_t * ui_wifi3;
extern void ui_event_wifi4(lv_event_t * e);
extern lv_obj_t * ui_wifi4;
extern void ui_event_wifi5(lv_event_t * e);
extern lv_obj_t * ui_wifi5;
extern void ui_event_wifi8(lv_event_t * e);
extern lv_obj_t * ui_wifi8;
extern void ui_event_wifi9(lv_event_t * e);
extern lv_obj_t * ui_wifi9;
extern void ui_event_wifi6(lv_event_t * e);
extern lv_obj_t * ui_wifi6;
extern void ui_event_wifi7(lv_event_t * e);
extern lv_obj_t * ui_wifi7;
extern void ui_event_wifi10(lv_event_t * e);
extern lv_obj_t * ui_wifi10;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

