// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen5 = NULL;
lv_obj_t * ui_Container9 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Container11 = NULL;
lv_obj_t * ui_Setting2 = NULL;
lv_obj_t * ui_Home3 = NULL;
lv_obj_t * ui_Wifi2 = NULL;
lv_obj_t * ui_Container12 = NULL;
lv_obj_t * ui_wifi2 = NULL;
lv_obj_t * ui_settings = NULL;
lv_obj_t * ui_games = NULL;
lv_obj_t * ui_games1 = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Image11 = NULL;
lv_obj_t * ui_games2 = NULL;
lv_obj_t * ui_Image23 = NULL;
lv_obj_t * ui_Image25 = NULL;
lv_obj_t * ui_games3 = NULL;
// event funtions
void ui_event_Screen5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Container9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Setting2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_Wifi2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_wifi2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen4_screen_init);
    }
}

// build funtions

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container9 = lv_obj_create(ui_Screen5);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 250);
    lv_obj_set_height(ui_Container9, 250);
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container9, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Container9, lv_color_hex(0x383838), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Container9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Container9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Container9, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_Container9);
    lv_img_set_src(ui_Image4, &ui_img_menu_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image4, 0);
    lv_obj_set_y(ui_Image4, -95);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container11 = lv_obj_create(ui_Screen5);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_width(ui_Container11, 100);
    lv_obj_set_height(ui_Container11, 30);
    lv_obj_set_x(ui_Container11, 0);
    lv_obj_set_y(ui_Container11, 80);
    lv_obj_set_align(ui_Container11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Setting2 = lv_img_create(ui_Container11);
    lv_img_set_src(ui_Setting2, &ui_img_settings_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_Setting2, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Setting2, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Setting2, -35);
    lv_obj_set_y(ui_Setting2, 0);
    lv_obj_set_align(ui_Setting2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Setting2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Setting2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Home3 = ui_Home_create(ui_Container11);
    lv_obj_set_x(ui_Home3, 0);
    lv_obj_set_y(ui_Home3, 0);

    ui_Wifi2 = lv_img_create(ui_Container11);
    lv_img_set_src(ui_Wifi2, &ui_img_wifi_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_Wifi2, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Wifi2, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Wifi2, 35);
    lv_obj_set_y(ui_Wifi2, 0);
    lv_obj_set_align(ui_Wifi2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Wifi2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Wifi2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container12 = lv_obj_create(ui_Screen5);
    lv_obj_remove_style_all(ui_Container12);
    lv_obj_set_width(ui_Container12, 200);
    lv_obj_set_height(ui_Container12, 133);
    lv_obj_set_x(ui_Container12, -3);
    lv_obj_set_y(ui_Container12, -9);
    lv_obj_set_align(ui_Container12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Container12, LV_OBJ_FLAG_FLOATING | LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags

    ui_wifi2 = lv_img_create(ui_Container12);
    lv_img_set_src(ui_wifi2, &ui_img_wifi_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_wifi2, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_wifi2, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_wifi2, -60);
    lv_obj_set_y(ui_wifi2, -40);
    lv_obj_set_align(ui_wifi2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifi2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifi2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_wifi2, 450);

    ui_settings = lv_img_create(ui_Container12);
    lv_img_set_src(ui_settings, &ui_img_settings_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_settings, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_settings, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_settings, 0);
    lv_obj_set_y(ui_settings, -40);
    lv_obj_set_align(ui_settings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settings, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_settings, 450);

    ui_games = lv_img_create(ui_Container12);
    lv_img_set_src(ui_games, &ui_img_stadia_controller_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_games, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_games, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_games, 60);
    lv_obj_set_y(ui_games, -40);
    lv_obj_set_align(ui_games, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_games, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_img_set_zoom(ui_games, 450);

    ui_games1 = lv_img_create(ui_Container12);
    lv_img_set_src(ui_games1, &ui_img_stadia_controller_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_games1, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_games1, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_games1, 60);
    lv_obj_set_y(ui_games1, 5);
    lv_obj_set_align(ui_games1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_games1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_img_set_zoom(ui_games1, 450);

    ui_Image6 = lv_img_create(ui_Container12);
    lv_img_set_src(ui_Image6, &ui_img_wifi_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_Image6, -60);
    lv_obj_set_y(ui_Image6, 5);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image6, 450);

    ui_Image11 = lv_img_create(ui_Container12);
    lv_img_set_src(ui_Image11, &ui_img_settings_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image11, 0);
    lv_obj_set_y(ui_Image11, 5);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image11, 450);

    ui_games2 = lv_img_create(ui_Container12);
    lv_img_set_src(ui_games2, &ui_img_stadia_controller_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_games2, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_games2, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_games2, 60);
    lv_obj_set_y(ui_games2, 50);
    lv_obj_set_align(ui_games2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_games2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_img_set_zoom(ui_games2, 450);

    ui_Image23 = lv_img_create(ui_Container12);
    lv_img_set_src(ui_Image23, &ui_img_settings_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_Image23, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image23, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image23, 0);
    lv_obj_set_y(ui_Image23, 50);
    lv_obj_set_align(ui_Image23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image23, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image23, 450);

    ui_Image25 = lv_img_create(ui_Container12);
    lv_img_set_src(ui_Image25, &ui_img_wifi_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_Image25, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_Image25, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_Image25, -60);
    lv_obj_set_y(ui_Image25, 50);
    lv_obj_set_align(ui_Image25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image25, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image25, 450);

    ui_games3 = lv_img_create(ui_Container12);
    lv_img_set_src(ui_games3, &ui_img_stadia_controller_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_games3, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_games3, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_games3, 60);
    lv_obj_set_y(ui_games3, 95);
    lv_obj_set_align(ui_games3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_games3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_img_set_zoom(ui_games3, 450);

    lv_obj_add_event_cb(ui_Container9, ui_event_Container9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Setting2, ui_event_Setting2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Wifi2, ui_event_Wifi2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifi2, ui_event_wifi2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen5, ui_event_Screen5, LV_EVENT_ALL, NULL);

}

void ui_Screen5_screen_destroy(void)
{
    if(ui_Screen5) lv_obj_del(ui_Screen5);

    // NULL screen variables
    ui_Screen5 = NULL;
    ui_Container9 = NULL;
    ui_Image4 = NULL;
    ui_Container11 = NULL;
    ui_Setting2 = NULL;
    ui_Home3 = NULL;
    ui_Wifi2 = NULL;
    ui_Container12 = NULL;
    ui_wifi2 = NULL;
    ui_settings = NULL;
    ui_games = NULL;
    ui_games1 = NULL;
    ui_Image6 = NULL;
    ui_Image11 = NULL;
    ui_games2 = NULL;
    ui_Image23 = NULL;
    ui_Image25 = NULL;
    ui_games3 = NULL;

}
