// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN6_H
#define UI_SCREEN6_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen6
extern void ui_Screen6_screen_init(void);
extern void ui_Screen6_screen_destroy(void);
extern void ui_event_Screen6(lv_event_t * e);
extern lv_obj_t * ui_Screen6;
extern void ui_event_Container16(lv_event_t * e);
extern lv_obj_t * ui_Container16;
extern lv_obj_t * ui_Container17;
extern void ui_event_Image4(lv_event_t * e);
extern lv_obj_t * ui_Image4;
extern void ui_event_BrightnessSlider(lv_event_t * e);
extern lv_obj_t * ui_BrightnessSlider;
extern void ui_event_brightness2(lv_event_t * e);
extern lv_obj_t * ui_brightness2;
extern lv_obj_t * ui_brightnessvalue;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

