// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_Container10 = NULL;
lv_obj_t * ui_Image17 = NULL;
lv_obj_t * ui_Container14 = NULL;
lv_obj_t * ui_Setting = NULL;
lv_obj_t * ui_Home1 = NULL;
lv_obj_t * ui_menu1 = NULL;
lv_obj_t * ui_Image22 = NULL;
lv_obj_t * ui_brightness3 = NULL;
// event funtions
void ui_event_Screen4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Image17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Setting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_menu1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_brightness3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container10 = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, 250);
    lv_obj_set_height(ui_Container10, 250);
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container10, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Container10, lv_color_hex(0x383838), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Container10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Container10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Container10, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image17 = lv_img_create(ui_Container10);
    lv_img_set_src(ui_Image17, &ui_img_arrow_back_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image17, -90);
    lv_obj_set_y(ui_Image17, 0);
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container14 = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_Container14);
    lv_obj_set_width(ui_Container14, 100);
    lv_obj_set_height(ui_Container14, 30);
    lv_obj_set_x(ui_Container14, 0);
    lv_obj_set_y(ui_Container14, 80);
    lv_obj_set_align(ui_Container14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Setting = lv_img_create(ui_Container14);
    lv_img_set_src(ui_Setting, &ui_img_settings_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_Setting, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Setting, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Setting, -35);
    lv_obj_set_y(ui_Setting, 0);
    lv_obj_set_align(ui_Setting, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Setting, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Setting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Home1 = ui_Home_create(ui_Container14);
    lv_obj_set_x(ui_Home1, 0);
    lv_obj_set_y(ui_Home1, 0);

    ui_menu1 = lv_img_create(ui_Container14);
    lv_img_set_src(ui_menu1, &ui_img_menu_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_menu1, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_menu1, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_menu1, 30);
    lv_obj_set_y(ui_menu1, 0);
    lv_obj_set_align(ui_menu1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_menu1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_menu1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image22 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image22, &ui_img_wifi_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_Image22, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image22, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image22, 0);
    lv_obj_set_y(ui_Image22, -95);
    lv_obj_set_align(ui_Image22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image22, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_brightness3 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_brightness3, &ui_img_light_mode_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_brightness3, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_brightness3, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_brightness3, lv_pct(0));
    lv_obj_set_y(ui_brightness3, lv_pct(-20));
    lv_obj_set_align(ui_brightness3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_brightness3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_brightness3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_brightness3, 700);
    lv_obj_set_style_radius(ui_brightness3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_brightness3, lv_color_hex(0x515151), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_brightness3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_brightness3, lv_color_hex(0x7A7979), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_brightness3, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_brightness3, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_brightness3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_brightness3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Image17, ui_event_Image17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Setting, ui_event_Setting, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_menu1, ui_event_menu1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_brightness3, ui_event_brightness3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen4, ui_event_Screen4, LV_EVENT_ALL, NULL);

}

void ui_Screen4_screen_destroy(void)
{
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_Container10 = NULL;
    ui_Image17 = NULL;
    ui_Container14 = NULL;
    ui_Setting = NULL;
    ui_Home1 = NULL;
    ui_menu1 = NULL;
    ui_Image22 = NULL;
    ui_brightness3 = NULL;

}
