// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_event_comp_Home_Home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_Home = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

// COMPONENT Home

lv_obj_t * ui_Home_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Home;
    cui_Home = lv_img_create(comp_parent);
    lv_img_set_src(cui_Home, &ui_img_home_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(cui_Home, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(cui_Home, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_align(cui_Home, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Home, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(cui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_HOME_NUM);
    children[UI_COMP_HOME_HOME] = cui_Home;
    lv_obj_add_event_cb(cui_Home, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Home, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_Home, ui_event_comp_Home_Home, LV_EVENT_ALL, children);
    ui_comp_Home_create_hook(cui_Home);
    return cui_Home;
}

