// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_HOME_H
#define _UI_COMP_HOME_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Home
#define UI_COMP_HOME_HOME 0
#define _UI_COMP_HOME_NUM 1
lv_obj_t * ui_Home_create(lv_obj_t * comp_parent);
void ui_event_comp_Home_Home(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
