// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

// COMPONENT dot

lv_obj_t * ui_dot_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_dot;
    cui_dot = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_dot);
    lv_obj_set_width(cui_dot, 10);
    lv_obj_set_height(cui_dot, 10);
    lv_obj_set_align(cui_dot, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_dot, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_dot, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_dot, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_dot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_DOT_NUM);
    children[UI_COMP_DOT_DOT] = cui_dot;
    lv_obj_add_event_cb(cui_dot, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_dot, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_dot_create_hook(cui_dot);
    return cui_dot;
}

