// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"
#include "ui_Screen2.h"
#include "ui_Screen3.h"
#include "ui_Screen4.h"
#include "ui_Screen5.h"
#include "ui_Screen6.h"
#include "ui_Screen7.h"
#include "ui_Screen8.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(
    ui_img_home_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/home_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_arrow_back_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/arrow_back_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_arrow_forward_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/arrow_forward_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_wifi_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/wifi_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_settings_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/settings_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_menu_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/menu_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_light_mode_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/light_mode_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_info_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/info_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_alarm_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/alarm_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_timer_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/timer_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_bluetooth_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/bluetooth_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_stadia_controller_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/stadia_controller_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
