// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen8 = NULL;
lv_obj_t * ui_Container13 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Spinner1 = NULL;
lv_obj_t * ui_home3 = NULL;
// event funtions
void ui_event_Screen8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_Image7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_home3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen8_screen_init(void)
{
    ui_Screen8 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container13 = lv_obj_create(ui_Screen8);
    lv_obj_remove_style_all(ui_Container13);
    lv_obj_set_width(ui_Container13, 250);
    lv_obj_set_height(ui_Container13, 250);
    lv_obj_set_align(ui_Container13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container13, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Container13, lv_color_hex(0x383838), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Container13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Container13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Container13, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_img_create(ui_Container13);
    lv_img_set_src(ui_Image7, &ui_img_arrow_back_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image7, -90);
    lv_obj_set_y(ui_Image7, 0);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_img_create(ui_Screen8);
    lv_img_set_src(ui_Image8, &ui_img_wifi_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image8, 0);
    lv_obj_set_y(ui_Image8, -95);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinner1 = lv_spinner_create(ui_Screen8, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 80);
    lv_obj_set_height(ui_Spinner1, 80);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0x797986), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0x00FF03), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 120, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner1, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Spinner1, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_home3 = lv_img_create(ui_Screen8);
    lv_img_set_src(ui_home3, &ui_img_home_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_home3, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_home3, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_home3, lv_pct(0));
    lv_obj_set_y(ui_home3, lv_pct(33));
    lv_obj_set_align(ui_home3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_home3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_home3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_home3, 450);
    lv_obj_set_style_radius(ui_home3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_home3, lv_color_hex(0x515151), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_home3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_home3, lv_color_hex(0x7A7979), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_home3, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_home3, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_home3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_home3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_home3, lv_color_hex(0x515151), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_home3, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_grad_color(ui_home3, lv_color_hex(0x7A7979), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_grad_dir(ui_home3, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_Image7, ui_event_Image7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_home3, ui_event_home3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen8, ui_event_Screen8, LV_EVENT_ALL, NULL);

}

void ui_Screen8_screen_destroy(void)
{
    if(ui_Screen8) lv_obj_del(ui_Screen8);

    // NULL screen variables
    ui_Screen8 = NULL;
    ui_Container13 = NULL;
    ui_Image7 = NULL;
    ui_Image8 = NULL;
    ui_Spinner1 = NULL;
    ui_home3 = NULL;

}
