// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

// COMPONENT Time

lv_obj_t * ui_Time_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Time;
    cui_Time = lv_label_create(comp_parent);
    lv_obj_set_width(cui_Time, 64);
    lv_obj_set_height(cui_Time, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(cui_Time, 40);
    lv_obj_set_y(cui_Time, 0);
    lv_obj_set_align(cui_Time, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Time, "00");
    lv_obj_set_style_text_font(cui_Time, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_TIME_NUM);
    children[UI_COMP_TIME_TIME] = cui_Time;
    lv_obj_add_event_cb(cui_Time, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Time, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Time_create_hook(cui_Time);
    return cui_Time;
}

