// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: Smartwatch

#include "../ui.h"

lv_obj_t * ui_watch_analog = NULL;
lv_obj_t * ui_bg_2 = NULL;
lv_obj_t * ui_clock = NULL;
lv_obj_t * ui_dots = NULL;
lv_obj_t * ui_clock_group = NULL;
lv_obj_t * ui_sec = NULL;
lv_obj_t * ui_min = NULL;
lv_obj_t * ui_hour = NULL;
lv_obj_t * ui_dots_group = NULL;
lv_obj_t * ui_dot16 = NULL;
lv_obj_t * ui_dot17 = NULL;
// event funtions
void ui_event_watch_analog(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        min_Animation(ui_min, 0);
        hour_Animation(ui_hour, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_watch_digital, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_watch_digital_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_watch_digital, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_watch_digital_screen_init);
    }
}

// build funtions

void ui_watch_analog_screen_init(void)
{
    ui_watch_analog = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_watch_analog, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_watch_analog, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_watch_analog, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bg_2 = lv_image_create(ui_watch_analog);
    lv_image_set_src(ui_bg_2, &ui_img_bg1_png);
    lv_obj_set_width(ui_bg_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bg_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bg_2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bg_2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_bg_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_clock = lv_label_create(ui_watch_analog);
    lv_obj_set_width(ui_clock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_clock, 2);
    lv_obj_set_y(ui_clock, 75);
    lv_obj_set_align(ui_clock, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_clock, "03   27");
    lv_obj_set_style_text_color(ui_clock, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_clock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_clock, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dots = lv_label_create(ui_watch_analog);
    lv_obj_set_width(ui_dots, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dots, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dots, 2);
    lv_obj_set_y(ui_dots, 72);
    lv_obj_set_align(ui_dots, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_dots, ":");
    lv_obj_set_style_text_color(ui_dots, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dots, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dots, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clock_group = lv_obj_create(ui_watch_analog);
    lv_obj_set_width(ui_clock_group, 350);
    lv_obj_set_height(ui_clock_group, 350);
    lv_obj_set_align(ui_clock_group, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_clock_group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_clock_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clock_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sec = lv_image_create(ui_clock_group);
    lv_image_set_src(ui_sec, &ui_img_clockwise_sec_png);
    lv_obj_set_width(ui_sec, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sec, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sec, 0);
    lv_obj_set_y(ui_sec, -67);
    lv_obj_set_align(ui_sec, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sec, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_sec, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_sec, 15, 155);
    lv_image_set_rotation(ui_sec, 12000);

    ui_min = lv_image_create(ui_clock_group);
    lv_image_set_src(ui_min, &ui_img_clockwise_min_png);
    lv_obj_set_width(ui_min, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_min, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_min, 0);
    lv_obj_set_y(ui_min, -75);
    lv_obj_set_align(ui_min, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_min, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_min, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_min, 9, 153);

    ui_hour = lv_image_create(ui_clock_group);
    lv_image_set_src(ui_hour, &ui_img_clockwise_hour_png);
    lv_obj_set_width(ui_hour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hour, 0);
    lv_obj_set_y(ui_hour, -45);
    lv_obj_set_align(ui_hour, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hour, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_hour, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_hour, 9, 93);

    ui_dots_group = lv_obj_create(ui_watch_analog);
    lv_obj_set_width(ui_dots_group, 20);
    lv_obj_set_height(ui_dots_group, 50);
    lv_obj_set_x(ui_dots_group, -10);
    lv_obj_set_y(ui_dots_group, 0);
    lv_obj_set_align(ui_dots_group, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_dots_group, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_dots_group, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_dots_group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dots_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dots_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_dots_group, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_dots_group, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot16 = lv_obj_create(ui_dots_group);
    lv_obj_set_width(ui_dot16, 10);
    lv_obj_set_height(ui_dot16, 10);
    lv_obj_set_align(ui_dot16, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_dot16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot16, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot17 = lv_obj_create(ui_dots_group);
    lv_obj_set_width(ui_dot17, 6);
    lv_obj_set_height(ui_dot17, 6);
    lv_obj_set_align(ui_dot17, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_dot17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot17, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot17, lv_color_hex(0x676767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_watch_analog, ui_event_watch_analog, LV_EVENT_ALL, NULL);

}

void ui_watch_analog_screen_destroy(void)
{
    if(ui_watch_analog) lv_obj_del(ui_watch_analog);

    // NULL screen variables
    ui_watch_analog = NULL;
    ui_bg_2 = NULL;
    ui_clock = NULL;
    ui_dots = NULL;
    ui_clock_group = NULL;
    ui_sec = NULL;
    ui_min = NULL;
    ui_hour = NULL;
    ui_dots_group = NULL;
    ui_dot16 = NULL;
    ui_dot17 = NULL;

}
