// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: Smartwatch

#ifndef UI_WATCH_ANALOG_H
#define UI_WATCH_ANALOG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_watch_analog
extern void ui_watch_analog_screen_init(void);
extern void ui_watch_analog_screen_destroy(void);
extern void ui_event_watch_analog(lv_event_t * e);
extern lv_obj_t * ui_watch_analog;
extern lv_obj_t * ui_bg_2;
extern lv_obj_t * ui_clock;
extern lv_obj_t * ui_dots;
extern lv_obj_t * ui_clock_group;
extern lv_obj_t * ui_sec;
extern lv_obj_t * ui_min;
extern lv_obj_t * ui_hour;
extern lv_obj_t * ui_dots_group;
extern lv_obj_t * ui_dot16;
extern lv_obj_t * ui_dot17;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

