// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Container7;
extern void ui_event_Container11(lv_event_t * e);
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_Label11;
extern void ui_event_brightness(lv_event_t * e);
extern lv_obj_t * ui_brightness;
extern void ui_event_Container15(lv_event_t * e);
extern lv_obj_t * ui_Container15;
extern lv_obj_t * ui_Label12;
extern void ui_event_about(lv_event_t * e);
extern lv_obj_t * ui_about;
extern void ui_event_Container19(lv_event_t * e);
extern lv_obj_t * ui_Container19;
extern lv_obj_t * ui_Label14;
extern void ui_event_about1(lv_event_t * e);
extern lv_obj_t * ui_about1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

